pub const BORDER_THICKNESS_SIDE: usize = 1;
pub const BORDER_THICKNESS: usize = BORDER_THICKNESS_SIDE * 2;

pub const MIN_INPUT_CONTENT_HEIGHT: usize = 1;
pub const MIN_INPUT_HEIGHT: usize = MIN_INPUT_CONTENT_HEIGHT + BORDER_THICKNESS_SIDE;
pub const MAX_INPUT_RATIO: f32 = 0.3;
